
name: Build and Deploy
on:
  push:
    branches: [main]
jobs:
  test_me:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: testing nginx server ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            rm -rf /var/www/l-video-editor
            cd /var/www/
            mkdir l-video-editor
            cd l-video-editor
            git clone https://github.com/mix0000/l-video-editor.git .
            npm install
            npm run prod
            systemctl restart nginx
